<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\MongoDBException;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends DocumentRepository
{
    public function findTenOrderedByGrade()
    {
        try {
            return $this->createQueryBuilder()
                ->sort('grade', 'ASC')
                ->limit(10)

                ->getQuery()
                ->execute();
        } catch (MongoDBException $e) {
        }
    }
}
