<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\MongoDBException;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends DocumentRepository
{
    public function findLimitedOrderedByGrade()
    {
        try {
            return $this->createQueryBuilder()
                ->sort('score', 'DESC')
                ->limit(6)

                ->getQuery()
                ->execute();
        } catch (MongoDBException $e) {
        }
    }

    public function countGrade($grade)
    {
        try {
            return $this->createQueryBuilder()
                ->field('grade')->equals($grade)
                ->getQuery()->execute()->count();
        } catch (MongoDBException $e) {
        }
    }

    public function countScore($score)
    {
        try {
            return $this->createQueryBuilder()
                ->field('score')->equals($score)
                ->getQuery()->execute()->count();
        } catch (MongoDBException $e) {
        }
    }




}
